server:
  port: 8080
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunfeng008/spring-clould-examples/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                         # git仓库的账号
          password:                                         # git仓库的密码
      label: master                                         #仓库的分支
    bus:
      trace:
        enabled: true                                       #跟踪总线事件

  rabbitmq:
      host: localhost
      port: 5672
      username: root
      password: root

#注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

